name: flutter_websocket_manager_plugin
description: A Flutter plugin that maintains WebSocket connections in background on Android and iOS.
version: 1.0.2

homepage: https://github.com/ThearyCoding/flutter_websocket_manager_plugin
repository: https://github.com/ThearyCoding/flutter_websocket_manager_plugin
issue_tracker: https://github.com/ThearyCoding/flutter_websocket_manager_plugin/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.engapp.websocket_manager
        pluginClass: WebsocketManagerPlugin
      ios:
        pluginClass: WebsocketManagerPlugin
